### ISSUE TITLE
License discussion

### ISSUE THREAD

**Issue by tb148** [ScratchAddons/extension#5]
Since this is an userscript collection, I think it is better to make the license compatible with common licenses, so I recommend **GPL**. For example, if a user requests his **GPL-licensed** userscript ([griffpatch's dev tool](https://github.com/griffpatch/Scratch3-Dev-Tools) for example) to be added, we will have to reject it, and I don't want this to happen! So I recommend using **GPL**.
There are still [incompatible licenses](https://www.gnu.org/licenses/license-list.html#GPLIncompatibleLicenses), but they are usually very rare so it becomes a small issue after switching to **GPL**.
What license do you think we should choose?

**Comment by WorldLanguages** [comment]
Makes sense. I'll change the license.
